import loanercart from "../assets/loanercart.png"
import setup from "../assets/mysetup.png"
import stock from "../assets/stock.png"

function Report(){
    return(
        <div className="border-neutral-900 pb-4 lg:mb-20 border-b-4">
            <div className="flex flex-wrap">
                <div className="w-full lg:w-1/2">
                    <div className="flex flex-col items-center lg:items-start">
                        <h1 className="pb-16 text-3xl font-thin tracking-tight lg:mt-16 lg:text-6xl">F24 WT Report</h1>
<p className="my-2 max-w-xl py-6 font-light tracking-tighter">Greetings, and welcome to my Summer 2024 Coop WT report. I hope through reading this report, I can explain and document the many experiences I have had throughout my first co-op work term. You'll find an overview of the university environment and my experiences working in it, as well as a look at some of the notable things I was involved in. Through this report, I aim to share the highlights of my journey and the growth I’ve achieved along the way.</p>

<p className="my-2 max-w-xl py-6 font-light tracking-tighter">I work for the University of Guelph, specifically for the CCS Managed Desktops department. I'm sure the University does not need much of an introduction; founded in 1964 and primarily having strong roots in agriculture and animal research, U of G is one of the most accredited schools in the world. U of G actually has one of the top veterinary programs in the world, and since I had the liberty of starting in OVC before the term ended, I can see why the degree is state of the art. OVC is a sprawling building with lots of professionals working together to care for animals. I found it interesting that OVC itself is actually a combination of multiple different buildings, including the Stewart, Former VMI, ACC, Small Animal Centre, the Main Building (aptly named), and a few more that go by varying names. This lends itself to a very unique interior that has lots of interesting and varied places to go, all under one roof. But back to Johnston Hall, where I spent the bulk of my first term, I worked specifically in MD, a sub-organization of CCS, where our service involves handling all tech-related issues for university employees. At MD, we manage the deployment of all employee computers at the school, using various tools and software to ensure proper management. The area most connected with my job in a CS sense would be network management and information systems. While this isn't computer science in a coding sense, and many might look down on the job, I have come to realize just how integral these roles are to keeping the campus running smoothly.</p>

<p className="my-2 max-w-xl py-6 font-light tracking-tighter">I had a few different goals for the term that I’ll briefly list now. Firstly, I aimed to improve my oral communication skills this term, specifically in customer service, an area where I had previously encountered challenges. I worked towards this goal by actively engaging in more client interactions, such as handling door buzzer requests and meeting requests. I measured my success by following up before closing tickets to gauge their satisfaction and making sure that I encouraged clients to reach out for further help as a courtesy. Secondly, I sought to enhance my time management and multitasking skills during this work term to perform my IT tasks more effectively, particularly with tools like Footprints, Active Directory, and Microsoft Config Manager. I achieved this by planning my days, maintaining a list of critical tasks, and setting reminders to stay on track. My success was measured by the speed and efficiency with which I completed my tickets, ensuring a professional standard throughout. Finally, I aimed to tackle a higher quantity and more complex tasks during the less busy summer term, which allowed me to expand my IT knowledge and improve my problem-solving skills. This involved creating new SOPs and contributing to documentation to streamline handling uncommon tickets. I measured my success by comparing the complexity of new tasks with those I had handled previously and evaluating the improvements in my ability to diagnose and address various issues.</p>

<p className="my-2 max-w-xl py-6 font-light tracking-tighter">In terms of developing new goals related to my tasks, I tried to take some more initiative with tasks, improve my troubleshooting skills, and enhance the speed at which I could resolve issues. As I took on more complex tasks, I believe I achieved these goals effectively, becoming more comfortable and proficient at the job.</p>

<p className="my-2 max-w-xl py-6 font-light tracking-tighter">I think that I learned most of the skills I wanted. I would have liked to learn more about networking and IT automation workflows, such as learning more about Office 365 specifics and tools like PowerAutomate. These would represent advanced offshoots of the IT work that I was already doing as a student technician. They would introduce more interesting complexities that could be useful not only in the fall work term but also in future networking and IT system jobs, potentially including QA Engineering or Network Administration roles. Additionally, these skills would provide a good background in a software development environment as well.</p>

<p className="my-2 max-w-xl py-6 font-light tracking-tighter">Specifically in terms of technologies that I wanted to work with, I listed PowerAutomate, which I didn't get to use, but I also wanted to work with Active Directory, Microsoft Endpoint Manager, Footprints, and the Office 365 Suite of tools that I did use. These tools are integral to IT, networking, and information systems jobs. Footprints is a widely used ticketing system, and understanding it is important for other service jobs as well. Active Directory (AD) and Microsoft Endpoint Configuration Manager (MECM) are critical for managing and securing endpoint devices in many companies. Having a working knowledge of these applications is vital for many networking and IT administration roles I am interested in pursuing. Office 365 is essential because it is one of the most common suites of applications used in professional environments. Skills in navigating and using these apps are valuable for a variety of jobs, even outside of the computer science field, such as management, administration, or analytics roles.</p>

<p className="my-2 max-w-xl py-6 font-light tracking-tighter">Reflecting on my goals and learning outcomes, I am happy to report significant progress in enhancing my customer service skills and interactions. I believe that I successfully engaged with a variety of clients, leveraging even challenging interactions to gain valuable insights on handling difficult situations. This allowed me to improve my ability to manage client relations and encourage open communication through follow-ups and personal outreach. In terms of work ethic, I consistently met the goal of completing my tickets promptly, with response times averaging only an hour or two, and planned my tasks effectively to accommodate any unforeseen issues. Additionally, I expanded my responsibilities by tackling more complex tasks, including intricate software installations that required multiple steps and attention to detail, as well as troubleshooting. I also collaborated with a fellow Co-op student on developing a new guide for the upcoming term to help new Co-op students, contributing to its content and ensuring its accessibility by creating and proofreading several SOPs for our CCS SharePoint. Overall, I believe that I successfully achieved my goals related to customer service, timeliness, and task complexity, while also contributing meaningfully to the MD team.</p>

<p className="my-2 max-w-xl py-6 font-light tracking-tighter">An overview of my job would be providing support to clients who pay for the managed desktops services at our school. This could range from helping to install special or paid apps like Adobe Acrobat Pro 2020, providing user guidance and troubleshooting, building Windows devices for users, rebuilding and repairing devices, assisting with the setup of new devices, and helping on-site with various other issues users might encounter. I would say the most unique and interesting aspect of my job was the sheer variety of tasks performed on any given day. Thanks to the ticketing system and the range of problems that occur on campus, I was never bored with my tasks. Some days I was troubleshooting a monitor, while other times I was building a high-end computer or setting up engineering computers. The variety kept the work engaging. I got to visit nearly every building on campus to help with various issues, which was enriching personally, as I usually stick to only the necessary buildings during school terms. The skills needed for the job included having solid foundations in time management, problem compartmentalization, critical thinking, and being friendly and personable with clients. I believe that many of my sociable skills were developed on the job and through previous public-facing roles, such as working at Sobeys, rather than in class. However, my critical thinking skills were definitely honed during coding courses, where I learned to brainstorm multiple solutions to problems and break them down into manageable steps. Being computer-literate was also essential for swift troubleshooting and resolution, and I developed this literacy both through classes and extensive use of computers at home.</p>

<p className="my-2 max-w-xl py-6 font-light tracking-tighter">I hope that by reading this site, you will understand that IT is not a job to be dismissed lightly; it is integral to the success of organizations. Even in roles that might seem lowly, you can still learn many new skills and hone both personal and technical abilities that will help you succeed in the future, even if you don't plan to pursue a career in IT. Personally, I have greatly enjoyed my first work term here, and I hope that I have conveyed this in a way that is both interesting and insightful, shedding light on my experiences both technically and professionally, as well as personally.</p>
                    </div>
                </div>
                <div className="w-1/2 h-1/2 flex flex-col items-center justify-center p-4 space-y-4">
                <img src={setup} className="rounded-lg"></img>
                <p className="mt-2 text-center ">My desk, with teams and footprints open</p>
                <img src={stock} className="rounded-lg"></img>
                <p className="mt-2 text-center ">The stock room, where all new parts and computers are kept to be built for clients</p>
                <img src={loanercart} className="rounded-lg"></img>
                <p className="mt-2 text-center ">The loaner cart, which houses loaner PCs that we give out when we are rebuilding client PCs</p>
                </div>
            </div>
        </div>
    );

}

export default Report